<?php

namespace Database\Seeders;

use App\Models\Alimento;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AlimentoSeeder extends Seeder
{
    public function run()
    {
        // Desativa verificações de chave estrangeira para melhor performance
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Alimento::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $alimentos = [
            [
                'nome' => 'Batata inglesa',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.020,
                'creche_integral_per_capita' => 0.040,
                'pre_parcial_per_capita' => 0.015,
                'pre_integral_per_capita' => 0.030,
                'fundamental_parcial_per_capita' => 0.020,
                'fundamental_integral_per_capita' => 0.040,
                'eja_per_capita' => 0.025,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 1.00,
                'incidencia_fundamental_integral' => 1.00,
                'incidencia_eja' => 0.90,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Cenoura',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.020,
                'creche_integral_per_capita' => 0.030,
                'pre_parcial_per_capita' => 0.015,
                'pre_integral_per_capita' => 0.025,
                'fundamental_parcial_per_capita' => 0.020,
                'fundamental_integral_per_capita' => 0.030,
                'eja_per_capita' => 0.010,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 1.00,
                'incidencia_fundamental_integral' => 1.00,
                'incidencia_eja' => 0.80,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Coentro',
                'unidade_medida' => 'maço',
                'creche_parcial_per_capita' => 0.002,
                'creche_integral_per_capita' => 0.003,
                'pre_parcial_per_capita' => 0.002,
                'pre_integral_per_capita' => 0.003,
                'fundamental_parcial_per_capita' => 0.002,
                'fundamental_integral_per_capita' => 0.003,
                'eja_per_capita' => 0.001,
                'incidencia_creche_parcial' => 0.80,
                'incidencia_creche_integral' => 0.85,
                'incidencia_pre_parcial' => 0.80,
                'incidencia_pre_integral' => 0.85,
                'incidencia_fundamental_parcial' => 0.50,
                'incidencia_fundamental_integral' => 0.55,
                'incidencia_eja' => 0.30,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Tomate',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.008,
                'creche_integral_per_capita' => 0.012,
                'pre_parcial_per_capita' => 0.006,
                'pre_integral_per_capita' => 0.009,
                'fundamental_parcial_per_capita' => 0.008,
                'fundamental_integral_per_capita' => 0.012,
                'eja_per_capita' => 0.005,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 0.75,
                'incidencia_fundamental_integral' => 0.80,
                'incidencia_eja' => 0.60,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Beterraba',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.006,
                'creche_integral_per_capita' => 0.010,
                'pre_parcial_per_capita' => 0.004,
                'pre_integral_per_capita' => 0.008,
                'fundamental_parcial_per_capita' => 0.005,
                'fundamental_integral_per_capita' => 0.009,
                'eja_per_capita' => 0.003,
                'incidencia_creche_parcial' => 0.50,
                'incidencia_creche_integral' => 0.55,
                'incidencia_pre_parcial' => 0.40,
                'incidencia_pre_integral' => 0.45,
                'incidencia_fundamental_parcial' => 0.45,
                'incidencia_fundamental_integral' => 0.50,
                'incidencia_eja' => 0.30,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Alface',
                'unidade_medida' => 'maço',
                'creche_parcial_per_capita' => 0.003,
                'creche_integral_per_capita' => 0.005,
                'pre_parcial_per_capita' => 0.004,
                'pre_integral_per_capita' => 0.006,
                'fundamental_parcial_per_capita' => 0.005,
                'fundamental_integral_per_capita' => 0.007,
                'eja_per_capita' => 0.003,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 0.80,
                'incidencia_fundamental_integral' => 0.85,
                'incidencia_eja' => 0.70,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Pimentão',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.003,
                'creche_integral_per_capita' => 0.005,
                'pre_parcial_per_capita' => 0.003,
                'pre_integral_per_capita' => 0.005,
                'fundamental_parcial_per_capita' => 0.003,
                'fundamental_integral_per_capita' => 0.005,
                'eja_per_capita' => 0.002,
                'incidencia_creche_parcial' => 0.60,
                'incidencia_creche_integral' => 0.65,
                'incidencia_pre_parcial' => 0.60,
                'incidencia_pre_integral' => 0.65,
                'incidencia_fundamental_parcial' => 0.40,
                'incidencia_fundamental_integral' => 0.45,
                'incidencia_eja' => 0.30,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Goiaba',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.040,
                'creche_integral_per_capita' => 0.060,
                'pre_parcial_per_capita' => 0.030,
                'pre_integral_per_capita' => 0.050,
                'fundamental_parcial_per_capita' => 0.020,
                'fundamental_integral_per_capita' => 0.030,
                'eja_per_capita' => 0.015,
                'incidencia_creche_parcial' => 0.30,
                'incidencia_creche_integral' => 0.35,
                'incidencia_pre_parcial' => 0.25,
                'incidencia_pre_integral' => 0.30,
                'incidencia_fundamental_parcial' => 0.20,
                'incidencia_fundamental_integral' => 0.25,
                'incidencia_eja' => 0.15,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Arroz',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.100,
                'creche_integral_per_capita' => 0.180,
                'pre_parcial_per_capita' => 0.120,
                'pre_integral_per_capita' => 0.200,
                'fundamental_parcial_per_capita' => 0.140,
                'fundamental_integral_per_capita' => 0.220,
                'eja_per_capita' => 0.100,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 1.00,
                'incidencia_fundamental_integral' => 1.00,
                'incidencia_eja' => 0.95,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Feijão',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.060,
                'creche_integral_per_capita' => 0.100,
                'pre_parcial_per_capita' => 0.070,
                'pre_integral_per_capita' => 0.120,
                'fundamental_parcial_per_capita' => 0.080,
                'fundamental_integral_per_capita' => 0.140,
                'eja_per_capita' => 0.050,
                'incidencia_creche_parcial' => 1.00,
                'incidencia_creche_integral' => 1.00,
                'incidencia_pre_parcial' => 1.00,
                'incidencia_pre_integral' => 1.00,
                'incidencia_fundamental_parcial' => 1.00,
                'incidencia_fundamental_integral' => 1.00,
                'incidencia_eja' => 0.90,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Carne bovina',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.050,
                'creche_integral_per_capita' => 0.080,
                'pre_parcial_per_capita' => 0.060,
                'pre_integral_per_capita' => 0.100,
                'fundamental_parcial_per_capita' => 0.070,
                'fundamental_integral_per_capita' => 0.120,
                'eja_per_capita' => 0.040,
                'incidencia_creche_parcial' => 0.80,
                'incidencia_creche_integral' => 0.85,
                'incidencia_pre_parcial' => 0.80,
                'incidencia_pre_integral' => 0.85,
                'incidencia_fundamental_parcial' => 0.70,
                'incidencia_fundamental_integral' => 0.75,
                'incidencia_eja' => 0.60,
                'disponivel_quinzena' => true,
                'ativo' => true
            ],
            [
                'nome' => 'Frango',
                'unidade_medida' => 'KG',
                'creche_parcial_per_capita' => 0.040,
                'creche_integral_per_capita' => 0.070,
                'pre_parcial_per_capita' => 0.050,
                'pre_integral_per_capita' => 0.090,
                'fundamental_parcial_per_capita' => 0.060,
                'fundamental_integral_per_capita' => 0.100,
                'eja_per_capita' => 0.035,
                'incidencia_creche_parcial' => 0.70,
                'incidencia_creche_integral' => 0.75,
                'incidencia_pre_parcial' => 0.70,
                'incidencia_pre_integral' => 0.75,
                'incidencia_fundamental_parcial' => 0.60,
                'incidencia_fundamental_integral' => 0.65,
                'incidencia_eja' => 0.50,
                'disponivel_quinzena' => true,
                'ativo' => true
            ]
        ];

        foreach ($alimentos as $alimento) {
            Alimento::create($alimento);
        }
    }
}