<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Aluno;
use App\Models\Escola;

class AlunoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // First, ensure all schools exist in the escolas table
        $escolas = [
            ['nome' => '02 DE JULHO', 'codigo_inep' => 'ESC001'],
            ['nome' => '15 DE JULHO', 'codigo_inep' => 'ESC002'],
            ['nome' => '25 DE JULHO', 'codigo_inep' => 'ESC003'],
            ['nome' => 'AMÉRICO TANURI - JUNCO', 'codigo_inep' => 'ESC004'],
            ['nome' => 'AMÉRICO TANURI - MANIÇOBA', 'codigo_inep' => 'ESC005'],
            ['nome' => 'ANÁLIA BARBOSA DE SOUZA', 'codigo_inep' => 'ESC006'],
            ['nome' => 'ANTONIO FRANCISCO DE OLIVEIRA', 'codigo_inep' => 'ESC007'],
            ['nome' => 'ARGEMIRO JOSE DA CRUZ', 'codigo_inep' => 'ESC008'],
            ['nome' => 'BOM JESUS - BARAÚNA', 'codigo_inep' => 'ESC009'],
            ['nome' => 'BOM JESUS - NH1', 'codigo_inep' => 'ESC010'],
            ['nome' => 'C.R.A. PROFª MAZZARELLO CAVALCANTI REIS DA ROCHA', 'codigo_inep' => 'ESC011'],
            ['nome' => 'CAIC - MISAEL AGUILAR', 'codigo_inep' => 'ESC012'],
            ['nome' => 'CAXANGÁ', 'codigo_inep' => 'ESC013'],
            ['nome' => 'CELSO CAVALCANTE DE CARVALHO', 'codigo_inep' => 'ESC014'],
            ['nome' => 'CENTRO SOCIAL URBANO - CSU', 'codigo_inep' => 'ESC015'],
            ['nome' => 'CORAÇÃO DE JESUS - JUREMA VERMELHA', 'codigo_inep' => 'ESC016'],
            ['nome' => 'CORAÇÃO DE JESUS - SERRA DA MADEIRA', 'codigo_inep' => 'ESC017'],
            ['nome' => 'DEPUTADO RAIMUNDO DA CUNHA LEITE', 'codigo_inep' => 'ESC018'],
            ['nome' => 'DOM AVELAR BRANDAO VILELA', 'codigo_inep' => 'ESC019'],
            ['nome' => 'DOUTOR EDSON RIBEIRO', 'codigo_inep' => 'ESC020'],
            ['nome' => 'DURVAL BARBOSA DA CUNHA', 'codigo_inep' => 'ESC021'],
            ['nome' => 'E.M.E.I. ADELAIDE MOREIRA BISPO', 'codigo_inep' => 'ESC022'],
            ['nome' => 'E.M.E.I. ADJALVA FERREIRA LIMA', 'codigo_inep' => 'ESC023'],
            ['nome' => 'E.M.E.I. AMÉLIA BORGES', 'codigo_inep' => 'ESC024'],
            ['nome' => 'E.M.E.I. AMÉLIA DUARTE', 'codigo_inep' => 'ESC025'],
            ['nome' => 'E.M.E.I. AMÉRICO TANURY - ABÓBORA', 'codigo_inep' => 'ESC026'],
            ['nome' => 'E.M.E.I. ANA MARIA MORGADO CHAVES', 'codigo_inep' => 'ESC027'],
            ['nome' => 'E.M.E.I. ANNA HILDA LEITE FARIAS', 'codigo_inep' => 'ESC028'],
            ['nome' => 'E.M.E.I. ARCENIO JOSÉ DA SILVA', 'codigo_inep' => 'ESC029'],
            ['nome' => 'E.M.E.I. ARLINDA ALVES VARJÃO', 'codigo_inep' => 'ESC030'],
            ['nome' => 'E.M.E.I. BEATRIZ ANGÉLICA MOTA', 'codigo_inep' => 'ESC031'],
            ['nome' => 'E.M.E.I. BOLIVAR SANTANA', 'codigo_inep' => 'ESC032'],
            ['nome' => 'E.M.E.I. BOM JESUS DOS NAVEGANTES', 'codigo_inep' => 'ESC033'],
            ['nome' => 'E.M.E.I. CAIC MISAEL AGUILAR', 'codigo_inep' => 'ESC034'],
            ['nome' => 'E.M.E.I. DILMA CALMON DE OLIVEIRA', 'codigo_inep' => 'ESC035'],
            ['nome' => 'E.M.E.I. EDIVÂNIA SANTOS CARDOSO', 'codigo_inep' => 'ESC036'],
            ['nome' => 'E.M.E.I. ELEOTÉRIO SOUZA', 'codigo_inep' => 'ESC037'],
            ['nome' => 'E.M.E.I. FRANCISCO PEREIRA DOS SANTOS', 'codigo_inep' => 'ESC038'],
            ['nome' => 'E.M.E.I. GABRIELA DE JESUS', 'codigo_inep' => 'ESC039'],
            ['nome' => 'E.M.E.I. IRMÃ ADILSON', 'codigo_inep' => 'ESC040'],
            ['nome' => 'E.M.E.I. IRMÃO ADEÍLSON', 'codigo_inep' => 'ESC041'],
            ['nome' => 'E.M.E.I. LÍDIA MARIA NOGUEIRA', 'codigo_inep' => 'ESC042'],
            ['nome' => 'E.M.E.I. LUIZ DE FREITAS', 'codigo_inep' => 'ESC043'],
            ['nome' => 'E.M.E.I. MARIA HELENA DA SILVA PEREIRA', 'codigo_inep' => 'ESC044'],
            ['nome' => 'E.M.E.I. MARIA HOZANA NUNES', 'codigo_inep' => 'ESC045'],
            ['nome' => 'E.M.E.I. MARIA JÚLIA RODRIGUES TANURI', 'codigo_inep' => 'ESC046'],
            ['nome' => 'E.M.E.I. MARIA SUELY MEDRADO ARAÚJO', 'codigo_inep' => 'ESC047'],
            ['nome' => 'E.M.E.I. MARIÁ VIANA TANURI', 'codigo_inep' => 'ESC048'],
            ['nome' => 'E.M.E.I. NAILDE DE SOUZA COSTA', 'codigo_inep' => 'ESC049'],
            ['nome' => 'E.M.E.I. NÉLIA DE SOUZA COSTA', 'codigo_inep' => 'ESC050'],
            ['nome' => 'E.M.E.I. NOSSA SENHORA DAS GROTAS - CARNAÍBA', 'codigo_inep' => 'ESC051'],
            ['nome' => 'E.M.E.I. NOSSO SENHOR DOS AFLITOS', 'codigo_inep' => 'ESC052'],
            ['nome' => 'E.M.E.I. PASSAGEM DO SARGENTO', 'codigo_inep' => 'ESC053'],
            ['nome' => 'E.M.E.I. PASTOR MANOEL MARQUES DE SOUZA', 'codigo_inep' => 'ESC054'],
            ['nome' => 'E.M.E.I. PREFEITO APRÍGIO DUARTE', 'codigo_inep' => 'ESC055'],
            ['nome' => 'E.M.E.I. PROFª HELOISA HELENA BENEVIDES FARIAS', 'codigo_inep' => 'ESC056'],
            ['nome' => 'E.M.E.I. PROFª JOANA RAMOS', 'codigo_inep' => 'ESC057'],
            ['nome' => 'E.M.E.I. VANDA GUERRA', 'codigo_inep' => 'ESC058'],
            ['nome' => 'E.M.R.T.I. SÃO JOSÉ', 'codigo_inep' => 'ESC059'],
            ['nome' => 'E.M.T.I. PROFª IRACEMA PEREIRA DA PAIXÃO', 'codigo_inep' => 'ESC060'],
            ['nome' => 'EDUCANDÁRIO JOÃO XXIII', 'codigo_inep' => 'ESC061'],
            ['nome' => 'ELISEU SANTOS', 'codigo_inep' => 'ESC062'],
            ['nome' => 'ESTAÇÃO DO SABER JOSÉ CARLOS TANURI', 'codigo_inep' => 'ESC063'],
            ['nome' => 'EURÍDICE RIBEIRO VIANA', 'codigo_inep' => 'ESC064'],
            ['nome' => 'EXTENSAO - BOLIVAR SANTANA', 'codigo_inep' => 'ESC065'],
            ['nome' => 'EXTENSAO - E.M.E.I. GENTIL DAMASIO DO NASCIMENTO', 'codigo_inep' => 'ESC066'],
            ['nome' => 'EXTENSAO - E.M.E.I. MARIA VIANA TANURI', 'codigo_inep' => 'ESC067'],
            ['nome' => 'EXTENSAO - MARIA MONTEIRO BACELAR', 'codigo_inep' => 'ESC068'],
            ['nome' => 'EXTENSAO - PRESIDENTE TANCREDO NEVES', 'codigo_inep' => 'ESC069'],
            ['nome' => 'FAMÍLIA UNIDA', 'codigo_inep' => 'ESC070'],
            ['nome' => 'GRACIOSA XAVIER RAMOS GOMES', 'codigo_inep' => 'ESC071'],
            ['nome' => 'HELENA ARAÚJO PINHEIRO', 'codigo_inep' => 'ESC072'],
            ['nome' => 'HELENA CELESTINO MAGALHÃES', 'codigo_inep' => 'ESC073'],
            ['nome' => 'JATOBÁ', 'codigo_inep' => 'ESC074'],
            ['nome' => 'JOÃO DIAS FERREIRA', 'codigo_inep' => 'ESC075'],
            ['nome' => 'JOÃO NEVES DE ALMEIDA', 'codigo_inep' => 'ESC076'],
            ['nome' => 'JOCA DE SOUZA OLIVEIRA', 'codigo_inep' => 'ESC077'],
            ['nome' => 'JOSÉ DE AMORIM', 'codigo_inep' => 'ESC078'],
            ['nome' => 'JOSÉ DIAS CAVALCANTE', 'codigo_inep' => 'ESC079'],
            ['nome' => 'JOSÉ MACÊDO DE ARAÚJO', 'codigo_inep' => 'ESC080'],
            ['nome' => 'JOSÉ NOGUEIRA DE ALMEIDA', 'codigo_inep' => 'ESC081'],
            ['nome' => 'JOSÉ RAMOS BORGES', 'codigo_inep' => 'ESC082'],
            ['nome' => 'LUIZ EDUARDO RODRIGUES', 'codigo_inep' => 'ESC083'],
            ['nome' => 'MARCÍLIO JOSÉ DE SOUZA', 'codigo_inep' => 'ESC084'],
            ['nome' => 'MARIA JOSÉ FARIAS', 'codigo_inep' => 'ESC085'],
            ['nome' => 'MARIA JOSÉ SILVA DE ARAÚJO', 'codigo_inep' => 'ESC086'],
            ['nome' => 'MARIA LUIZA ARAÚJO', 'codigo_inep' => 'ESC087'],
            ['nome' => 'MARIA MONTEIRO BACELAR', 'codigo_inep' => 'ESC088'],
            ['nome' => 'MARIANA DE SOUZA PEREIRA', 'codigo_inep' => 'ESC089'],
            ['nome' => 'MARIZETE ARAÚJO DO NASCIMENTO', 'codigo_inep' => 'ESC090'],
            ['nome' => 'MATINHA DE ALMEIDA', 'codigo_inep' => 'ESC091'],
            ['nome' => 'MERCÊS RAMOS DE SOUZA', 'codigo_inep' => 'ESC092'],
            ['nome' => 'MARIA JULIA RODRIGUES TANURI', 'codigo_inep' => 'ESC093'],
            ['nome' => 'MARIA MONTEIRO BACELAR', 'codigo_inep' => 'ESC094'],
            ['nome' => 'MARIANO RODRIGUES DE SOUZA', 'codigo_inep' => 'ESC095'],
            ['nome' => 'MIGUEL ÂNGELO DE SOUZA', 'codigo_inep' => 'ESC096'],
            ['nome' => 'NOSSA SENHORA DAS GROTAS - BOQUEIRÃO', 'codigo_inep' => 'ESC097'],
            ['nome' => 'NOSSA SENHORA DAS GROTAS-SEDE', 'codigo_inep' => 'ESC098'],
            ['nome' => 'NOSSA SENHORA RAINHA DOS ANJOS', 'codigo_inep' => 'ESC099'],
            ['nome' => 'OSORIO TELES DE MENEZES', 'codigo_inep' => 'ESC100'],
            ['nome' => 'PAULO FREIRE', 'codigo_inep' => 'ESC101'],
            ['nome' => 'PAULO VI', 'codigo_inep' => 'ESC102'],
            ['nome' => 'PEDRO DIAS', 'codigo_inep' => 'ESC103'],
            ['nome' => 'PONTAL', 'codigo_inep' => 'ESC104'],
            ['nome' => 'PREFEITO APRÍGIO DUARTE', 'codigo_inep' => 'ESC105'],
            ['nome' => 'PRESIDENTE TANCREDO NEVES', 'codigo_inep' => 'ESC106'],
            ['nome' => 'PROFª ANTONILA DA FRANÇA CARDOSO', 'codigo_inep' => 'ESC107'],
            ['nome' => 'PROFª ATANILHA LUZ ARAÚJO', 'codigo_inep' => 'ESC108'],
            ['nome' => 'PROFª BERNADETE BRAGA', 'codigo_inep' => 'ESC109'],
            ['nome' => 'PROFª CARMEM COSTA SANTOS', 'codigo_inep' => 'ESC110'],
            ['nome' => 'PROFª CRENILDES LUIZ BRANDÃO', 'codigo_inep' => 'ESC111'],
            ['nome' => 'PROFª DINORAH ALBERNAZ MELO DA SILVA', 'codigo_inep' => 'ESC112'],
            ['nome' => 'PROFª EDUALDINA DAMÁSIO', 'codigo_inep' => 'ESC113'],
            ['nome' => 'PROFª GUIOMAR LUSTOSA RODRIGUES', 'codigo_inep' => 'ESC114'],
            ['nome' => 'PROFª HAYDÉE FONSECA FALCÃO', 'codigo_inep' => 'ESC115'],
            ['nome' => 'PROFª IRACY NUNES DA SILVA', 'codigo_inep' => 'ESC116'],
            ['nome' => 'PROFª LEOPOLDINA LEAL', 'codigo_inep' => 'ESC117'],
            ['nome' => 'PROFª MARIA DE LOURDES DUARTE', 'codigo_inep' => 'ESC118'],
            ['nome' => 'PROFª MARIA FRANCA PIRES', 'codigo_inep' => 'ESC119'],
            ['nome' => 'PROFª MARIA JOSÉ LIMA DA ROCHA', 'codigo_inep' => 'ESC120'],
            ['nome' => 'PROFª MATILDE COSTA MEDRADO', 'codigo_inep' => 'ESC121'],
            ['nome' => 'PROFª OSCARLINA TANURI', 'codigo_inep' => 'ESC122'],
            ['nome' => 'PROFª TEREZINHA FERREIRA DE OLIVEIRA', 'codigo_inep' => 'ESC123'],
            ['nome' => 'PROFº CARLOS DA COSTA SILVA', 'codigo_inep' => 'ESC124'],
            ['nome' => 'PROFº JOSÉ PEREIRA DA SILVA', 'codigo_inep' => 'ESC125'],
            ['nome' => 'PROFº LUIS CURSINO DA FRANÇA CARDOSO', 'codigo_inep' => 'ESC126'],
            ['nome' => 'PROFº PEDRO RAIMUNDO RODRIGUES REGO', 'codigo_inep' => 'ESC127'],
            ['nome' => 'PROMENOR', 'codigo_inep' => 'ESC128'],
            ['nome' => 'RAIMUNDO CLEMENTINO DE SOUZA', 'codigo_inep' => 'ESC129'],
            ['nome' => 'RAIMUNDO MEDRADO PRIMO', 'codigo_inep' => 'ESC130'],
            ['nome' => 'RURAL DE MASSAROCA - ERUM', 'codigo_inep' => 'ESC131'],
            ['nome' => 'SANTA INÊS', 'codigo_inep' => 'ESC132'],
            ['nome' => 'SANTA TEREZINHA', 'codigo_inep' => 'ESC133'],
            ['nome' => 'SANTO ANTÔNIO', 'codigo_inep' => 'ESC134'],
            ['nome' => 'SÃO FRANCISCO DE ASSIS - MULUNGÚ', 'codigo_inep' => 'ESC135'],
            ['nome' => 'SÃO FRANCISCO DE ASSIS - NH2', 'codigo_inep' => 'ESC136'],
            ['nome' => 'SÃO JOSÉ', 'codigo_inep' => 'ESC137'],
            ['nome' => 'SÃO SEBASTIÃO', 'codigo_inep' => 'ESC138'],
            ['nome' => 'VEREADOR AMADEUS DAMÁSIO', 'codigo_inep' => 'ESC139'],
         ];

        foreach ($escolas as $escola) {
            Escola::firstOrCreate($escola);
        }

        // Now seed the alunos data for each school
        $alunosData = [
            // Page 1 data
            [
                'escola_nome' => '02 DE JULHO',
                'creche_parcial' => 37 + 13, // Manhã + Tarde
                'creche_integral' => 0,
                'pre_parcial' => 109, // Manhã
                'pre_integral' => 0,
                'fundamental_parcial' => 306 + 261, // Manhã + Tarde
                'fundamental_integral' => 96,
                'eja' => 12 + 27 + 96, // Integral + Manhã + Tarde
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => '15 DE JULHO',
                'creche_parcial' => 19,
                'creche_integral' => 0,
                'pre_parcial' => 34,
                'pre_integral' => 0,
                'fundamental_parcial' => 166 + 209,
                'fundamental_integral' => 18,
                'eja' => 33 + 18,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => '25 DE JULHO',
                'creche_parcial' => 23,
                'creche_integral' => 0,
                'pre_parcial' => 33,
                'pre_integral' => 0,
                'fundamental_parcial' => 60 + 135,
                'fundamental_integral' => 17,
                'eja' => 17,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'AMÉRICO TANURI - JUNCO',
                'creche_parcial' => 5,
                'creche_integral' => 0,
                'pre_parcial' => 2,
                'pre_integral' => 0,
                'fundamental_parcial' => 29,
                'fundamental_integral' => 17,
                'eja' => 24,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'AMÉRICO TANURI - MANICORA',
                'creche_parcial' => 0,
                'creche_integral' => 16,
                'pre_parcial' => 0,
                'pre_integral' => 19,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 40,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'ANÁLIA BARBOSA DE SOUZA',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 356 + 361,
                'fundamental_integral' => 0,
                'eja' => 104,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'ANTONIO FRANCISCO DE OLIVEIRA',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 15,
                'pre_integral' => 0,
                'fundamental_parcial' => 99 + 65,
                'fundamental_integral' => 12,
                'eja' => 12,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'ARGEMIRO JOSE DA CRUZ',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 372 + 379,
                'fundamental_integral' => 0,
                'eja' => 90,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'BOM JESUS - BARAÚNA',
                'creche_parcial' => 0,
                'creche_integral' => 2,
                'pre_parcial' => 0,
                'pre_integral' => 6,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 23,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'BOM JESUS - NH1',
                'creche_parcial' => 0,
                'creche_integral' => 12,
                'pre_parcial' => 0,
                'pre_integral' => 31,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 190,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CAC - MISAEL AGULLAR',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 655,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CAXANGA',
                'creche_parcial' => 1,
                'creche_integral' => 0,
                'pre_parcial' => 16,
                'pre_integral' => 0,
                'fundamental_parcial' => 24,
                'fundamental_integral' => 13,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CELSO CAVALCANTE DE CARVALHO',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 61 + 117 + 227,
                'fundamental_integral' => 0,
                'eja' => 34,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CENTRO SOCIAL URBANO - CSU',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 184 + 176,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CORAÇÃO DE JESUS - JUBEMA VERMELHA',
                'creche_parcial' => 13,
                'creche_integral' => 0,
                'pre_parcial' => 35,
                'pre_integral' => 0,
                'fundamental_parcial' => 19 + 33,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'CORAÇÃO DE JESUS - SERRA DA MADEIRA',
                'creche_parcial' => 0,
                'creche_integral' => 1,
                'pre_parcial' => 0,
                'pre_integral' => 8,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 32,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'C.R.A. PROFª MAZZARELLO CAVALCANTI REIS DA ROCHA',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 201 + 23 + 16,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'DEPUTADO RANNUNDO DA CUNHA LEITE',
                'creche_parcial' => 17,
                'creche_integral' => 0,
                'pre_parcial' => 16,
                'pre_integral' => 0,
                'fundamental_parcial' => 49 + 55,
                'fundamental_integral' => 10,
                'eja' => 10,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'DOM AVELAR BRANDAD VILELA',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 329 + 217,
                'fundamental_integral' => 0,
                'eja' => 74,
                'ano_letivo' => '2025'
            ],
            
            // Page 2 data
            [
                'escola_nome' => 'DOUTOR EDSON RIBIERO',
                'creche_parcial' => 16,
                'creche_integral' => 0,
                'pre_parcial' => 42,
                'pre_integral' => 0,
                'fundamental_parcial' => 14 + 47,
                'fundamental_integral' => 16,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'DURVAL BARBOSA DA CUNA',
                'creche_parcial' => 0,
                'creche_integral' => 11,
                'pre_parcial' => 0,
                'pre_integral' => 19,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 29,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EDUCANDÁRIO JOÃO XXIII',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 253 + 253,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'ELISEU SANTOS',
                'creche_parcial' => 0,
                'creche_integral' => 14,
                'pre_parcial' => 0,
                'pre_integral' => 36,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 148,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ADELAIDE MOREIRA BISPO',
                'creche_parcial' => 38 + 36,
                'creche_integral' => 0,
                'pre_parcial' => 49 + 50,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ADJALVA FERREIRA LIMA',
                'creche_parcial' => 40 + 32,
                'creche_integral' => 55,
                'pre_parcial' => 88 + 91,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I AMÉLIA BORGES',
                'creche_parcial' => 45 + 20,
                'creche_integral' => 0,
                'pre_parcial' => 22 + 36,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I AMÉLIA DUARTE',
                'creche_parcial' => 36 + 33,
                'creche_integral' => 58,
                'pre_parcial' => 95 + 92,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I AMÉRICO TANURY - ABÓRORA',
                'creche_parcial' => 19 + 20,
                'creche_integral' => 0,
                'pre_parcial' => 20 + 33,
                'pre_integral' => 0,
                'fundamental_parcial' => 14 + 12,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ANA MARIA MORGADO CHAVES',
                'creche_parcial' => 37 + 40,
                'creche_integral' => 0,
                'pre_parcial' => 81 + 86,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ANNA HILDA LEITE FARIAS',
                'creche_parcial' => 21,
                'creche_integral' => 0,
                'pre_parcial' => 20 + 42,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ARCENIO JOSÉ DA SUVA',
                'creche_parcial' => 3,
                'creche_integral' => 0,
                'pre_parcial' => 8,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I ARLINDA ALVES VARJÃO',
                'creche_parcial' => 34 + 60,
                'creche_integral' => 74,
                'pre_parcial' => 82 + 65,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  BEATRIZ ANGÉLICA MOTA',
                'creche_parcial' => 58 + 71,
                'creche_integral' => 0,
                'pre_parcial' => 119 + 96,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I BOLIVAR SANTANA',
                'creche_parcial' => 32 + 22,
                'creche_integral' => 34,
                'pre_parcial' => 46 + 53,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  BOM JESUS DOS NAVEGANTES',
                'creche_parcial' => 0,
                'creche_integral' => 22,
                'pre_parcial' => 41 + 37,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  CAIC MISAEL AGUILLAR',
                'creche_parcial' => 10 + 20,
                'creche_integral' => 106,
                'pre_parcial' => 57 + 56,
                'pre_integral' => 0,
                'fundamental_parcial' => 42 + 45,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  DILMA CALMON DE OLIVEIRA',
                'creche_parcial' => 24 + 24,
                'creche_integral' => 0,
                'pre_parcial' => 50 + 54,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  EDIVÂNIA SANTOS CARDOSO',
                'creche_parcial' => 40 + 56,
                'creche_integral' => 0,
                'pre_parcial' => 64 + 49,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  ELEOTÉRIO SOARES FONSÊCA',
                'creche_parcial' => 0,
                'creche_integral' => 28,
                'pre_parcial' => 0,
                'pre_integral' => 44,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  GENTIL DAMÁSIO DO NASCIMENTO',
                'creche_parcial' => 56 + 58,
                'creche_integral' => 0,
                'pre_parcial' => 63 + 61,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  HERBET MOUSE RODRIGUES',
                'creche_parcial' => 9,
                'creche_integral' => 0,
                'pre_parcial' => 24 + 31,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  IRMÃ REDENTA',
                'creche_parcial' => 38 + 23,
                'creche_integral' => 18,
                'pre_parcial' => 61 + 91,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  JANDIRA BORGES',
                'creche_parcial' => 22 + 26,
                'creche_integral' => 0,
                'pre_parcial' => 78 + 81,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  LENI LOPES DE ARAÚJO SANTOS',
                'creche_parcial' => 66 + 51,
                'creche_integral' => 52,
                'pre_parcial' => 76 + 92,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I  LUANA DA SUVA NASCIMENTO',
                'creche_parcial' => 42 + 40,
                'creche_integral' => 60,
                'pre_parcial' => 73 + 75,
                'pre_integral' => 0,
                'fundamental_parcial' => 0,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  LUZINETE DE OLIVEIRA',
                'creche_parcial' => 43 + 0, // Manhã + Tarde (S4 is unclear, treated as 0)
                'creche_integral' => 66,
                'pre_parcial' => 0 + 0, // No data for Pré-Escola Manhã/Tarde
                'pre_integral' => 0, // S4 is unclear
                'fundamental_parcial' => 83 + 76,
                'fundamental_integral' => 0,
                'eja' => 0 + 0, // No EJA data
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MANOEL ALVES DA MOTA',
                'creche_parcial' => 22 + 22,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 95 + 89,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA DE LOURDES DO VALLE ALMEIDA',
                'creche_parcial' => 55 + 36,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 85 + 53,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA FERREIRA DE SOUZA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 27,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 30,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA HELENA DA SILVA PEREIRA',
                'creche_parcial' => 46 + 44,
                'creche_integral' => 18,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 49 + 51,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA HOZANA NUNES',
                'creche_parcial' => 45 + 63,
                'creche_integral' => 64,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 73 + 88,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA JÚLIA RODRIGUES TANURI',
                'creche_parcial' => 44 + 39,
                'creche_integral' => 32,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 59 + 62,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIA SULY MEDRADO ARAÚJO',
                'creche_parcial' => 52 + 48,
                'creche_integral' => 20,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 48 + 40,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  MARIÁ VIANA TANURI',
                'creche_parcial' => 17 + 20,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 23 + 23,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I.  NAILDE DE SOUZA COSTA',
                'creche_parcial' => 56 + 58,
                'creche_integral' => 47,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 79 + 81,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. NÉLIA DE SOUZA COSTA',
                'creche_parcial' => 68 + 50,
                'creche_integral' => 30,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 99 + 77,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. NOSSA SENHORA DAS GROTAS - CARNAÍBA',
                'creche_parcial' => 5 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 24,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. NOSSO SENHOR DOS AFIITOS',
                'creche_parcial' => 46 + 43,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 69 + 69,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. PASSAGEM DO SARGENTO',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 7,
                'pre_parcial' => 6 + 0,
                'pre_integral' => 9,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. PASTOR MANOEL MARQUES DE SOUZA',
                'creche_parcial' => 45 + 41,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 60 + 48,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. PREFETTO APRÍGIO DUARTE',
                'creche_parcial' => 24 + 24,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 69 + 71,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. PROFª HELOISA HELENA BENEVIDES FARIAS',
                'creche_parcial' => 18 + 23,
                'creche_integral' => 19,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 73 + 74,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. PROFª JOANA RAMOS',
                'creche_parcial' => 10 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 24 + 9,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.E.I. VANDA GUERRA',
                'creche_parcial' => 56 + 58,
                'creche_integral' => 16,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 82 + 68,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.R.T.I. SÃO JOSÉ',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 27,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 59,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 424,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'E.M.T.I. PROFª IRACEMA PEREIRA DA PAIXÃO',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 149,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'ESTAÇÃO DO SABER JOSÉ CARLOS TANURI',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 194,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EURÍDICE RIBERO VIANA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 2,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 15,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 40,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO - BOLIVAR SANTANA',
                'creche_parcial' => 4 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 11,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO - E.M.E.I. GENTIL DAMASIO DO NASCIMENTO',
                'creche_parcial' => 38 + 18,
                'creche_integral' => 26,
                'pre_parcial' => 50 + 57,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO - E.M.E.I. LUZINETE DE OLIVEIRA/HELENA ARAÚJO PINHEIRO²',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 184,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 103,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 43,
                'eja' => 90 + 96,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO - E.M.E.I  MARIA VIANA TANURI',
                'creche_parcial' => 36 + 16,
                'creche_integral' => 36,
                'pre_parcial' => 63 + 55,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO E.M.E.I  NAILDE COSTA / JUA CRESCE MAIS / CENTENARIO',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 89,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'EXTENSÃO - MARIA MONTEIRO BACELAR',
                'creche_parcial' => 0 + 14,
                'creche_integral' => 3,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'FAMÍLIA UNIDA',
                'creche_parcial' => 7 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 14,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 18,
                'eja' => 13 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'GRACOSA XAVIER RAMOS GOMES',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 222,
                'eja' => 110 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'HELENA ARAÚJO PINHEIRO',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 175,
                'eja' => 166 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'HELENA CELESTINO MACALHÃES',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 366,
                'eja' => 331 + 97,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JATOBÁ',
                'creche_parcial' => 14 + 13,
                'creche_integral' => 0,
                'pre_parcial' => 14 + 34,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 17,
                'eja' => 28 + 60,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JOÃO DIAS FERREIRA',
                'creche_parcial' => 11 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 28,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 16,
                'eja' => 44 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JOÃO NEVES DE ALMEIDA',
                'creche_parcial' => 0 + 16,
                'creche_integral' => 23,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 32 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JOCA DE SOUZA OLIVEIRA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 192,
                'eja' => 165 + 68,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JOSÉ DE AMORIM',
                'creche_parcial' => 15 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 32,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 184,
                'eja' => 153 + 19,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JOSÉ PADILHA DE SOUZA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 137,
                'eja' => 159 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'JUDITE LEAL COSTA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 102,
                'eja' => 106 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'LINDAURA MARIA DE JESUS',
                'creche_parcial' => 0 + 7,
                'creche_integral' => 2,
                'pre_parcial' => 8 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'LÚCIA CARMEM SOBREIRA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 26,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 20,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 46,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'LUDGERO DE SOUZA COSTA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 19 + 0,
                'pre_integral' => 48,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 171,
                'eja' => 173 + 141,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MANDACARU',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 245,
                'eja' => 202 + 27,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MANOEL DE SOUZA BONFIM',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 74 + 78,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 62,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MANOEL GOMES MARTINS',
                'creche_parcial' => 12 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 22,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 71,
                'eja' => 51 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MANOEL LUIZ DA SILVA',
                'creche_parcial' => 13 + 12,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 46,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 12,
                'eja' => 12 + 39,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MANOEL NUMES AMORIM',
                'creche_parcial' => 4 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 20,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 50 + 31,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MARIA AMÉLIA DE SOUZA OLIVEIRA',
                'creche_parcial' => 16 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 20,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 0 + 51,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MARIA DO CARMO SÁ NOGUEIRA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 2,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 13,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 25,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MARIA JULIA RODRIGUES TANURI',
                'creche_parcial' => 56 + 41,
                'creche_integral' => 0,
                'pre_parcial' => 65 + 64,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 174 + 178,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MARIA MONTEIRO BACELAR¹',
                'creche_parcial' => 0 + 26,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 28,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 24,
                'eja' => 17 + 32,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MARIANO RODRIGUES DE SOUZA',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 18,
                'pre_parcial' => 14 + 22,
                'pre_integral' => 20,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 31,
                'eja' => 36 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'MIGUEL ÂNGELO DE SOUZA',
                'creche_parcial' => 25 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 31,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 0,
                'eja' => 21 + 82,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'NOSSA SEMHORA DAS GROTAS - BOQUERÃO',
                'creche_parcial' => 6 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 13,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 23,
                'eja' => 0 + 20,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'NOSSA SEMHORA DAS GROTAS-SEDE',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 129,
                'eja' => 131 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'NOSSA SEMHORA RAINHA DOS ANOS',
                'creche_parcial' => 6 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 10,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 10,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'OSORIO TELES DE MENEZES',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 50,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 52,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PAULO FREIRE',
                'creche_parcial' => 11 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 19,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 24,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PAULO VI',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 420,
                'eja' => 0 + 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PEDRO DIAS',
                'creche_parcial' => 0 + 0,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 84,
                'eja' => 29 + 30,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PONTAL',
                'creche_parcial' => 16 + 22,
                'creche_integral' => 0,
                'pre_parcial' => 0 + 40,
                'pre_integral' => 0,
                'fundamental_parcial' => 0 + 0,
                'fundamental_integral' => 34,
                'eja' => 53 + 69,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PREFEITO APRÍGIO DUARTE',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 115 + 113,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PRESIDENTE TANCREDO NEVES',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 384 + 401,
                'fundamental_integral' => 0,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PROFª ANTONILA DE FRANÇA CARDOSO',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 19,
                'pre_integral' => 0,
                'fundamental_parcial' => 51 + 60,
                'fundamental_integral' => 14,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                'escola_nome' => 'PROFª ATANILHA LUIZ ARAÚJO',
                'creche_parcial' => 0,
                'creche_integral' => 0,
                'pre_parcial' => 0,
                'pre_integral' => 0,
                'fundamental_parcial' => 56 + 0,
                'fundamental_integral' => 91,
                'eja' => 0,
                'ano_letivo' => '2025'
            ],
            [
                [
                    'escola_nome' => 'PROFª BERNADETE BRAGA',
                    'creche_parcial' => 9,
                    'creche_integral' => 0,
                    'pre_parcial' => 7,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 40,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª CARMEM COSTA SANTOS',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 353 + 314,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª CRENILDES LUIZ BRANDÃO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 122 + 120,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª DINORAH ALBERNAZ MELO DA SILVA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 338 + 337,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª EDUALDINA DAMÁSIO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 76 + 174 + 170,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª GUIOMAR LUSTOSA RODRIGUES',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 261 + 247,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª HAYDÉE FONSECA FALCÃO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 328 + 318,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª IRACY NUNES DA SILVA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 91 + 176 + 155,
                    'fundamental_integral' => 0,
                    'eja' => 4,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª LEOPOLDINA LEAL',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 307 + 293,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª MARIA DE LOURDES DUARTE',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 188 + 172,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª MARIA FRANCA PIRES³',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 176 + 227,
                    'fundamental_integral' => 0,
                    'eja' => 25,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª MARIA JOSÉ LIMA DA ROCHA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 333 + 342,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª MATILDE COSTA MEDRADO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 81 + 18,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª OSCARLINA TANURI',
                    'creche_parcial' => 0,
                    'creche_integral' => 8,
                    'pre_parcial' => 17,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 32 + 25,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFª TEREZINHA FERREIRA DE OLIVEIRA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 484 + 461,
                    'fundamental_integral' => 92,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFº CARLOS DA COSTA SILVA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 19,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 41 + 60,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFº JOSÉ PEREIRA DA SILVA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 288 + 283,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFº LUIS CURSINO DA FRANÇA CARDOSO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 24,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 64 + 86,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROFº PEDRO RAIMUNDO RODRIGUES REGO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 376 + 368,
                    'fundamental_integral' => 69,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'PROMENOR',
                    'creche_parcial' => 65,
                    'creche_integral' => 0,
                    'pre_parcial' => 42 + 42,
                    'pre_integral' => 43,
                    'fundamental_parcial' => 23 + 88 + 80,
                    'fundamental_integral' => 0,
                    'eja' => 130 + 130 + 123,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'RAIMUNDO CLEMENTINO DE SOUZA',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 72 + 48 + 74,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'RAIMUNDO MEDRADO PRIMO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 35 + 7,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 98 + 92,
                    'fundamental_integral' => 0,
                    'eja' => 133 + 99,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'RURAL DE MASSAROCA ERUM',
                    'creche_parcial' => 8,
                    'creche_integral' => 0,
                    'pre_parcial' => 4,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 76,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SANTA INÊS',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 39 + 326 + 310,
                    'fundamental_integral' => 0,
                    'eja' => 41,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SANTA TEREZINHA',
                    'creche_parcial' => 0,
                    'creche_integral' => 27,
                    'pre_parcial' => 0,
                    'pre_integral' => 44,
                    'fundamental_parcial' => 55 + 32,
                    'fundamental_integral' => 0,
                    'eja' => 82 + 76,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SANTO ANTÓNIO',
                    'creche_parcial' => 0,
                    'creche_integral' => 0,
                    'pre_parcial' => 0,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 309 + 252,
                    'fundamental_integral' => 0,
                    'eja' => 0,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SÃO FRANCISCO DE ASSIS - MULUNGÚ',
                    'creche_parcial' => 0,
                    'creche_integral' => 3,
                    'pre_parcial' => 0,
                    'pre_integral' => 9,
                    'fundamental_parcial' => 23,
                    'fundamental_integral' => 0,
                    'eja' => 35,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SÃO FRANCISCO DE ASSIS-NH2',
                    'creche_parcial' => 0,
                    'creche_integral' => 10,
                    'pre_parcial' => 7 + 10,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 33 + 83 + 64,
                    'fundamental_integral' => 0,
                    'eja' => 33 + 100 + 74,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SÃO JOSÉ',
                    'creche_parcial' => 0,
                    'creche_integral' => 9,
                    'pre_parcial' => 19 + 8,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 24 + 32,
                    'fundamental_integral' => 0,
                    'eja' => 43 + 49,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'SÃO SEBASTIÃO',
                    'creche_parcial' => 0,
                    'creche_integral' => 7,
                    'pre_parcial' => 11,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 34,
                    'fundamental_integral' => 0,
                    'eja' => 52,
                    'ano_letivo' => '2025'
                ],
                [
                    'escola_nome' => 'VEREADOR AMADEUS DAMASIO',
                    'creche_parcial' => 0,
                    'creche_integral' => 10,
                    'pre_parcial' => 23,
                    'pre_integral' => 0,
                    'fundamental_parcial' => 51,
                    'fundamental_integral' => 0,
                    'eja' => 84,
                    'ano_letivo' => '2025'
                ]
            ]
            
        ];

        foreach ($alunosData as $data) {
            // If the data is an array of arrays (nested), process each one
            if (isset($data[0]) && is_array($data[0])) {
                foreach ($data as $nestedData) {
                    $escola = Escola::where('nome', $nestedData['escola_nome'])->first();
                    
                    if ($escola) {
                        Aluno::create([
                            'escola_id' => $escola->id,
                            'creche_parcial' => $nestedData['creche_parcial'],
                            'creche_integral' => $nestedData['creche_integral'],
                            'pre_parcial' => $nestedData['pre_parcial'],
                            'pre_integral' => $nestedData['pre_integral'],
                            'fundamental_parcial' => $nestedData['fundamental_parcial'],
                            'fundamental_integral' => $nestedData['fundamental_integral'],
                            'eja' => $nestedData['eja'],
                            'ano_letivo' => $nestedData['ano_letivo']
                        ]);
                    }
                }
            } else {
                // Normal processing for non-nested data
                $escola = Escola::where('nome', $data['escola_nome'])->first();
                
                if ($escola) {
                    Aluno::create([
                        'escola_id' => $escola->id,
                        'creche_parcial' => $data['creche_parcial'],
                        'creche_integral' => $data['creche_integral'],
                        'pre_parcial' => $data['pre_parcial'],
                        'pre_integral' => $data['pre_integral'],
                        'fundamental_parcial' => $data['fundamental_parcial'],
                        'fundamental_integral' => $data['fundamental_integral'],
                        'eja' => $data['eja'],
                        'ano_letivo' => $data['ano_letivo']
                    ]);
                }
            }
        }
    }
}